[theme]
base = "light"
primaryColor = "#003366"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A1A2E"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
